### ISSUE TITLE
add parent node

### ISSUE THREAD

**Issue by Bonnev** [drichard/mindmaps#89]
I started a mind map from Root and after some time, I realized I want to add a parent to Root (so Root should have been the first child of another root). This is currently not possible and the workaround to what I want (to go through all the nodes) is not a nice one.

**Comment by drichard** [comment]
Hi there,

You should be able to just copy (CMD/CTRL + C) the root node and paste it
(CMD/CTRL +V) back onto the root node. This will copy the root onto a child
node and then you can remove the branches from the old root.



On 17 December 2019 at 7:50:28 pm, Bonnev (notifications@github.com) wrote:

I started a mind map from Root and after some time, I realized I want to
add a parent to Root (so Root should have been the first child of another
root). This is currently not possible and the workaround to what I want (to
go through all the nodes) is not a nice one.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/drichard/mindmaps/issues/89?email_source=notifications&email_token=AACSNW4RB6LESOV55B2ZQ6TQZCHFHA5CNFSM4J3X3QW2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IA7J5VA>,
or unsubscribe

**Comment by Bonnev** [comment]
@drichard Wow, ok.. I didn't think of that 😅. Alright, but it still sounds like a hard feature to find/figure out. I can leave is as a low-priority suggestion, but if you want, you can close the issue.
And thanks! Love the project!
